source 'https://cdn.cocoapods.org/'
source 'https://github.com/sybrin-innovations/Sybrin.iOS.Pods.git'

# Uncomment the next line to define a global platform for your project
# platform :ios, '12.4'

target 'simulatorsample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for simulatorsample
  pod 'Sybrin.iOS.Identity', '1.9.1'
  pod 'Sybrin.iOS.Biometrics', '1.2.1'

end
